name: npm docs to pdf
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'docs/**.md'
      - 'docs/images/**'
      - '.github/workflows/*yml'
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install mdpdf -g
      - run: mdpdf docs/README.md
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: docs
      #    path: pdfs
      #- uses: mikeal/publish-to-github-action@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #n    BRANCH_NAME: 'main'
